apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-api
  template:
    metadata:
      labels:
        app: banking-api
    spec:
      containers:
        - name: banking-api
          image: banking-api-image:latest
          ports:
            - containerPort: 9000
