apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pg-frontend-image:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_GATEWAY
              value: "https://dev.payfi.co.in/"
